### PR TITLE
Added electric_charge function and test cases

### PR DESCRIPTION
**Pull request by nrb1324**
As @namurphy requested I added a function that returns the actual charge as a `Quantity` along with some basic test cases.

### CODE REVIEW

**Comment by nrb1324** [comment]
I've fixed those and pushed to my branch, so I think they should be fixed. Thanks, I didn't have my editor set up properly.

**Comment by StanczakDominik** [comment]
The changes look good! I'm not 100% sure the pep8 changes you've made to accommodate the bot went through, as it tends to update the list to the current state. Did you perhaps amend the commit and force push to the branch? That's clean in terms of commit history but might have broken the bot somehow (not sure). Could you please take a look at it?

Anyway, I'll be merging this soon- i might fix the pep8 stuff if you don't get to it by then. Thanks for the fix!

**Comment by nrb1324** [comment]
Thanks @StanczakDominik. I hadn't committed properly, I don't quite have the hang of it yet.

**Comment by StanczakDominik** [comment]
Then I believe you've found the best way to learn! Thanks for cleaning this up.

Closes #103.

**Pull request merged**
