### PR TITLE
Final 0.1.1 fixes

### LINKED ISSUE #415: update README for v0.1 release
Announce it on the README!

### LINKED ISSUE #421: Create and update CHANGELOG.rst
List changes for v0.1 and open a new heading for v0.1.1

### PR DESCRIPTION
**Pull request by StanczakDominik**
Closes #421, closes #415, follow-up-fixes earlier #466 issue.

### CODE REVIEW

**Comment by StanczakDominik** [comment]
Applying [Cadair's earlier suggestion](https://github.com/PlasmaPy/PlasmaPy/issues/183#issuecomment-391398745), I realized a few things:

1. Cython seems to work
2. plasmapy.test() seems to work (with pytest-astropy)
3. python setup.py test also checks our .rst docs for doctests, which is awesome
4. there's a few .rst failures which I'm going to fix now, and I'm going to switch our custom testing infrastructure to python setup.py test with pytest-astropy. This will also simplify explaining how to run tests to new peeps.

**Comment by StanczakDominik** [comment]
Oh yeah, to make it explicit... Now is not the time for switching tests. I'm going to do minimal changes before 0.1.1.

**Comment by StanczakDominik** [comment]
@namurphy if you find the time I'd appreciate if you could take a look at 4b83020 to make sure these changes are what is intended. Still... any fixes should probably wait until after 0.1.1.

**Comment by namurphy** [comment]
@StanczakDominik - Yes, those changes look good.  Thanks!

**Pull request merged**
