### PR TITLE
Refactor main __init__.py

### PR DESCRIPTION
**Pull request by namurphy**
This pull request includes a few relatively minor updates to `plasmapy/__init__.py` that are related to readability, PEP8iness, and exception handling.

I removed `# coveralls: ignore` in a bunch of places, since things like `except ImportError` and `raise ImportError` are set to be ignored in our `.coveragerc` file.

### CODE REVIEW

**Comment by namurphy** [comment]
Looks like distutils has some good functionality that will help with checking to make sure dependent packages 📦 meet the minimum requirements.

**Comment by StanczakDominik** [comment]
The tests are falling perfectly into the problem raised in #195. I'll add parametrize and update this branch - it's a cool trick, so please look into it once I push it!

**Comment by StanczakDominik** [comment]
Here's an explanation of why I keep raving about this thing.

As you implemented this:
```bash
plasmapy-dev) [~/Code/PlasmaPy]$ pytest plasmapy/utils/tests/test_import_helpers.py 
============================================================================================================= test session starts =============================================================================================================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/dominik/Code/PlasmaPy, inifile: setup.cfg
collected 2 items                                                                                                                                                                                                                              

plasmapy/utils/tests/test_import_helpers.py ..

========================================================================================================== 2 passed in 0.91 seconds ===========================================================================================================
```

Which is fine and dandy. Except that if one of your tests crashes, the others will not be carried out! Now, what could instead be done is moving the `for` loops out of your test functions and into `pytest.mark.parametrize`, like this:

```python
# this is where the spirit of the for loop has moved on to
@pytest.mark.parametrize(['older_version', 'newer_version'],
                         zip(_create_different_versions(_python_version, 'older'),
                             _create_different_versions(_python_version, 'newer')))
def test_check_python(older_version, newer_version):
    """Test that check_python will raise an ImportError when
    minimum_python_version is newer than the current version, and will
    not raise an ImportError when minimum_python_version is the same
    as or older than the current version."""

    # this function now handles a "single" case (see further comments)
    with pytest.raises(ImportError):
        check_python(minimum_python_version=newer_version)
        raise Exception(
            "check_python is not raising an exception when it should be "
            f"raising one, with python_version = {_python_version} and "
            f"newer_version = {newer_version}")

    try:
        check_python(minimum_python_version=older_version)
    except ImportError as e:
        raise ImportError(
            "check_python is raising an exception when it should not be "
            f"raising one, with python_version = {_python_version} and "
            f"older_version = {older_version}") from e
```

And that gets us

```bash
(plasmapy-dev) [~/Code/PlasmaPy]$ pytest plasmapy/utils/tests/test_import_helpers.py 
============================================================================================================= test session starts =============================================================================================================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/dominik/Code/PlasmaPy, inifile: setup.cfg
collected 6 items                                                                                                                                                                                                                              

plasmapy/utils/tests/test_import_helpers.py ......

========================================================================================================== 6 passed in 0.98 seconds ===========================================================================================================
```

Six independent tests which are safe from individual ones crashing!

So yeah. In all honesty though, I went ahead of myself there and this example is not that great - what this case needs is 12 independent tests, as the tests for `older_version` are actually independent from `newer_version`.

So I guess I'll just go ahead and do that so pep8 stops screaming at us.

**Comment by StanczakDominik** [comment]
And by the way, if you think adding `pytest.mark.parametrize` here was overkill... I completely agree.

**Comment by namurphy** [comment]
I had been thinking about using pytest.parametrize for this one but tentatively decided against it since the tests were not that extensive and didn't really fit that greatly into that setup. The sole hesitation I have about pytest.parametrize is that it can be confusing to a newcomer to Python, but besides that, it is fantastic and I have been trying to use it when it is appropriate. I still need to learn more about class based testing though. 

Thank you!

**Comment by namurphy** [comment]
I want to check first whether this has the correct behavior for raising an ImportError in Python 2.7 before merging (which might not be for a few days), but besides that it looks ready to merge.

**Comment by namurphy** [comment]
Right now I am seriously contemplating this solution, which exactly has the desired behavior:
```Python
try:
    f""
except SyntaxError:
    raise ImportError("PlasmaPy requires Python 3.6 or later.  All hail the f-strings!")
```
The headache is that `from .utils import check_python, check_versions` requires going through the `utils/__init__.py` which then raises a bunch of f-string related syntax errors.  Sigh!

**Comment by StanczakDominik** [comment]
Crud, sorry if I came off as rude, then. My assumptions ("Nick forgot about parametrize!") tend to be pretty bad. My sincerest apologies.

I do think the benefits to testing outweigh the slightly bigger difficulty for newbies - and the latter might end up slightly more knowledgeable about proper testing. That's a risk I'd be willing to take.

We could, I suppose, keep utils py2 compliant, but honestly... I'd be leaning towards mostly ignoring the issue, maybe testing it ourselves once in a while or just once... It's python 2, if we procrastinate dealing with this for 2 (or however many till that's dropped) years it'll actually cease to be a problem. That's a rare opportunity!

**Comment by namurphy** [comment]
No worries whatsoever!  I think I've earned my reputation for mediocre tests with `test_parameters.py`, but I'm gradually getting better at testing. 😹

**Comment by namurphy** [comment]
I am getting confused by the following error:
```
Processing /home/circleci/project
    Complete output from command python setup.py egg_info:
    Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-8rx09wfm-build/setup.py", line 84, in <module>
        get_debug_option(PACKAGENAME))
      File "/tmp/pip-8rx09wfm-build/astropy_helpers/astropy_helpers/setup_helpers.py", line 117, in get_debug_option
        fromlist=['debug'])[0]
      File "/tmp/pip-8rx09wfm-build/astropy_helpers/astropy_helpers/version_helpers.py", line 299, in get_pkg_version_module
        mod = __import__(packagename + '.version', fromlist=fromlist)
      File "/tmp/pip-8rx09wfm-build/plasmapy/__init__.py", line 40, in <module>
        import_helpers.check_versions(__minimum_versions__)
    NameError: name 'import_helpers' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-8rx09wfm-build/
Exited with code 1
```

**Pull request merged**
