### PR TITLE
Appease Ruff in `nullpoint`

### PR DESCRIPTION
**Pull request by JaydenR2305**
Resolves PERF401 error raised in #2238 by using list comprehensions in the `nullpoint` module

### CODE REVIEW

**Comment by JaydenR2305** [comment]
@namurphy Should I add a changelog entry for this?

**Comment by namurphy** [comment]
> @namurphy Should I add a changelog entry for this?

I think it'd be fine either way!  I'll add the "no changelog entry needed" label, but will leave it up to you whether you want to add one or not.

**Comment by JaydenR2305** [comment]
According to the coverage report we are missing 37 lines that were previously being tested. Maybe I made a typo somewhere?

**Comment by namurphy** [comment]
I think I've noticed at times that preliminary coverage results sometimes get posted before tests finish.  Not sure why.  It looks like the coverage results are showing that everything is being covered now, so this looks set to merge.  Thank you for doing this!

**Review by namurphy — APPROVED** [review]

**Pull request merged**
