### PR TITLE
Edit the changelog before the 0.7.0 release

### PR DESCRIPTION
**Pull request by namurphy**
This PR is to make some updates to changelog entries for our 0.7.0 release, following up on #1207.

### CODE REVIEW

**Comment by namurphy** [comment]
Following #1226...

- [ ] Double check that each changelog entry has the correct pull request number.

**Comment by namurphy** [comment]
- [ ] Make sure hypothesis link works in 1125

**Comment by rocco8773** [comment]
The link in change log `1125.trivial` needs to be repaired. Unfortunately you can't nest back-ticks w/ explicit links. At least I haven't found a way.

**Comment by StanczakDominik** [comment]
All right; I will merge this now and roll the release out this week! I'll branch it off the merged commit for this one, so `main` should be safe to merge stuff into.

**Pull request merged**
