### PR TITLE
Add giles to circleci

### PR DESCRIPTION
**Pull request by Cadair**
I have written a little bot that will add documentation preview links to your PRs. If you want to use it you need to merge this PR and go here: https://github.com/apps/giles and add the app to the repository.

It gives you a thing that looks like this:

screenshot_20180306_184829

Like this PR: https://github.com/Cadair/giles/pull/3

### CODE REVIEW

**Comment by namurphy** [comment]
Thank you, @Cadair!  I'll do that once the tests pass.

**Comment by Cadair** [comment]
@namurphy if you turn it on I will trigger a rebuild and you can see if it works.

**Comment by namurphy** [comment]
> @namurphy if you turn it on I will trigger a rebuild and you can see if it works.

Done.  Probably.

**Comment by namurphy** [comment]
This is wonderful!  Thank you!

**Comment by StanczakDominik** [comment]
I just wanted to say this looks really neat. Looking forward to using it!

**Pull request merged**
