### PR TITLE
additions to getting ready to contribute page

### LINKED ISSUE #2001: User testing of contributor guide pages by new contributor on Windows
In #1656, we did an overhaul of the contributor guide pages on [getting ready to contribute](https://docs.plasmapy.org/en/latest/contributing/getting_ready.html) and the [code contribution workflow](https://docs.plasmapy.org/en/latest/contributing/workflow.html).  While updating these pages, I went through the steps on Linux, but attempted to include instructions for Windows and macOS.

It would be incredibly helpful for someone who hasn't contributed to an open source project before to try out these steps on Windows, and provide suggestions and feedback on how we could improve it.  

The suggestions and feedback could either be in the form of replies to this issue, or a pull request by a new contributor that updates the guide directly.  For the latter, the guides are at [`docs/contributing/getting_ready.rst`](https://github.com/PlasmaPy/PlasmaPy/blob/main/docs/contributing/getting_ready.rst) and [`docs/contributing/workflow.rst`](https://github.com/PlasmaPy/PlasmaPy/blob/main/docs/contributing/workflow.rst) and are written in [reStructuredText](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html).  

Many thanks!

Similar to: #2002

### PR DESCRIPTION
**Pull request by martha889**
## Description

Have added changes as mentioned in #2001 

## Related issues

Closes #2001

### CODE REVIEW

**Review by namurphy — APPROVED** [review]
@martha889 — thank you for testing the instructions on Windows and making this contribution!  I had two minor suggestions but it looks just about ready to merge.  

One last thing...could you add your name to [`docs/about/credits.rst`](https://github.com/martha889/PlasmaPy/edit/martha889_plasmapy/docs/about/credits.rst) to make sure that you get credit for the contribution? 

Thanks again!

**Comment by pheuer** [comment]
@namurphy Did we have a solution to these failing tests? It looks like that issue with the synthetic radiography rearing it's ugly head again...

**Comment by namurphy** [comment]
It looks like one of the main reasons this test is failing is that `ipykernel` isn't being found, which isn't related to this pull request, and might be an upstream error with the CI.  If it's an upstream error, there's a good chance it'll get fixed without us having to do anything, but I'll look into it if it persists.  In the meantime, we should pay attention to the **CI / Python 3.10, pinned dependencies** check and ignore the ones that are failing above.

**Comment by namurphy** [comment]
@martha889 — Thank you!  This is set to merge after the (unrelated) issue with the tests gets resolved.

**Pull request merged**
