### PR TITLE
Handle `Quantity` objects in `call_string()`

### LINKED ISSUE #337: Make call_string work with Quantity objects
The [`call_string`](https://github.com/PlasmaPy/PlasmaPy/blob/28156768b242564265e33b3baf8ae231f1a7c166/plasmapy/utils/pytest_helpers.py#L82) function in `utils` is designed to return a string of a function call, which is often really useful to put into error messages.  An example is:
```Python
>>> from plasmapy.utils import call_string
>>> def f(x, y=2): return x + y
>>> call_string(f, 1, {'y': 2})
'f(1, y=2)'
```
However, `call_string` does not work so well with Quantity objects:
```Python
>>> import astropy.units as u
>>> call_string(f, 5 * u.m)
'f(<Quantity 5. m>)'
```
Since we generally do `import astropy.units as u`, we probably should make `call_string` behave like this:
```Python
>>> call_string(f, 5 * u.m)
'f(5 * u.m)'
```
This is very related to #331.  Thanks!

### PR DESCRIPTION
**Pull request by ritiek**
Closes #337 and #331.

For example, now passing a `Quantity` object to `call_string` results in following output:
```python
>>> from plasmapy.utils import call_string
>>> import astropy.units as u
>>> def f(x, y, z):
...        pass
>>> call_string(f, 5 * u.m, {'y': 8*u.m, 'z': 5*u.kg})
'f(5.0 * u.m, y=8.0 * u.m, z=5.0 * u.kg)'
```

However, I personally find this a bit more readable :smile::
```python
'f(5.0*u.m, y=8.0*u.m, z=5.0*u.kg)'
```

What do you guys think?

### CODE REVIEW

**Comment by StanczakDominik** [comment]
In arguments, I think it's reasonable to go for no spaces between operators. I think pycharm was shouting at me for that, at least.

Do you think you could also implement this in PlasmaBlob.__repr__? That would close #331 as well!

**Comment by namurphy** [comment]
Yeah, since `call_string` is mostly used in error messages, using the more compact notation that you suggested sounds good to me!

**Comment by StanczakDominik** [comment]
That "?". :D

**Comment by ritiek** [comment]
Okay, `call_string` now works with `PlasmaBlob.__repr__` too:

```python
>>> from plasmapy.classes.plasma import PlasmaBlob
>>> import astropy.units as u

>>> T_e = 5 * 11e3 * u.K
>>> n_e = 1e23 * u.cm ** -3
>>> Z = 2.5
>>> particle = 'p'
>>> blob = PlasmaBlob(T_e=T_e,
...                   n_e=n_e,
...                   Z=Z,
...                   particle=particle)
>>> blob
PlasmaBlob(T_e=55000.0*u.K, n_e=1e+23*u.cm**-3, particle='p', Z=2.5)
# before
# PlasmaBlob(T_e=55000.0 K, n_e=1e+23 1 / cm3, particle=p, Z=2.5)
```

I'll fix the tests in a moment.

**Pull request merged**
