### PR TITLE
Parallelize `Tracker` in `synthetic_radiography`

### LINKED ISSUE #1728: Implement parallel processing for `charged_particle_radiography.Tracker`
Particle tracing in the `charged_particle_radiography.Tracker` class is an [embarrassingly parallelizable problem ](https://en.wikipedia.org/wiki/Embarrassingly_parallel), but the calculations are currently being performed in serial. Execution time is limited by processing the interpolation steps. Implementing parallel processing using [the multiprocessing library ](https://docs.python.org/3/library/multiprocessing.html) should allow a ~3-4x speed increase in tracing on laptops and very large increases on computing resources with more cores. This would significantly improve the module and make it feasible to run large batches of simulations for things like training machine learning algorithms.

Only the push step of the algorithm needs to be parallelized. The code should probably split particles into groups (#/ processing core) and then push them in parallel, stopping each process independently when the particles have left the grid(s). 

There are a few challenges to doing this: 
- The grids (from which fields for each particle are interpolated) are large (often >1 GB) and so replicating them in memory for each core is undesirable, especially on smaller computers. They are read-only, so it should definitely be possible to hold the grid in [shared memory](https://docs.python.org/3/library/multiprocessing.shared_memory.html) for use by all the processes. I'm not sure how this would work in detail, or whether it would be worth making this optional (maybe if the RAM is available, making copies of the grid will allow faster interpolation?). 
- The structure of the code needs minor modifications to make it compatible with parallel processing. The `_push` and `run` methods will need to be modified.

### PR DESCRIPTION
**Pull request by JaydenR2305**
Attempt to solve embarrassingly parallelizable problem outlined in #1728 

Resolves #1728

### CODE REVIEW

**Comment by JaydenR2305** [comment]
I seem to be getting a strange pickle error... 

```py
TypeError: ('Could not serialize object of type HighLevelGraph', '<ToPickle: HighLevelGraph with 1 layers.\n<dask.highlevelgraph.HighLevelGraph object at 0x7f2f48c782d0>\n 0. 139840971823616\n>')
```

**Comment by JaydenR2305** [comment]
image

Is there a way around this?

**Comment by pheuer** [comment]
@namurphy is in the process of configuring some new [ruff rules](https://beta.ruff.rs/docs/rules/#error-ple), and he may not have flagged all these old functions to disable the rule checking on them. First try merging in main to see if he's done this on a subsequent PR 

If not, I think you need to add `# noqa: PLR0912` to the first line of the function call. I think this is in main already now: 

```python

 def _make_grid(  # noqa: C901, PLR0912
        self,
        start: Union[int, float, u.Quantity],
        stop: Union[int, float, u.Quantity],
        num=100,
        units=None,
        **kwargs,
    ):
```

**Comment by JaydenR2305** [comment]
@pheuer Thank you! Ruff is definitely more strict. I put up a prototype, but I seem to be getting nothing but noise on the synthetic radiograph.

**Pull request closed without merging**
