### PR TITLE
Resolving Issue #844, fixing warnings

### PR DESCRIPTION
**Pull request by suzannenie**
- [ ] I have added a changelog entry for this pull request.

- [ ] If adding new functionality, I have added tests and
      docstrings.

- [ ] I have fixed any newly failing tests.

Progress toward issue #844 
Fixes warnings up to plasmapy/diagnostics/tests/test_langmuir.py (all files except the last four files).

### CODE REVIEW

**Comment by suzannenie** [comment]
pre-commit.ci autofix

**Review by StanczakDominik — CHANGES_REQUESTED** [review]
Hey @suzannenie, @tlee0818, @andrewsheng2, @mahimapannala, and @itsraashi,

so, okay, first up, since it's the first time I'm reviewing a 5-author PR, I have a question to ask of you. Did some of you do some insane workstation hopping while working on this, or is this a group project? In either case, that's amazing and I'd love to hear a bit about the story behind that 😄

secondly, the PR itself looks great and I'm reading [171 warnings](https://github.com/PlasmaPy/PlasmaPy/runs/4424061797?check_suite_focus=true) compared to [227 on the main branch](https://github.com/PlasmaPy/PlasmaPy/runs/4366725874?check_suite_focus=true), which is great progress! I do have a question in there (scroll down a little!) about warnings raised from doctests, but all in all, this looks great - thank you all for doing this!

**Comment by suzannenie** [comment]
Hi @StanczakDominik, 
This is a group project. We're all taking a software class together and our final project is to contribute to an open-source project of our choice. 
Thank you for your detailed comments. One thing to note is regarding your comment about particle_class.py; I only added a complete example to one of the tests, as the other two already had one complete example and one where a warning was triggered.
Thanks again and please let us know if there's anything else that we're missing!

**Comment by suzannenie** [comment]
pre-commit.ci autofix

**Comment by namurphy** [comment]
> This is a group project. We're all taking a software class together and our final project is to contribute to an open-source project of our choice.

That's exciting to hear!  Thank you for making this contribution!

**Review by StanczakDominik — APPROVED** [review]
> This is a group project. We're all taking a software class together and our final project is to contribute to an open-source project of our choice.



> One thing to note is regarding your comment about particle_class.py; I only added a complete example to one of the tests, as the other two already had one complete example and one where a warning was triggered.

Ah, yeah, that that was me doing a cursory glance on the changed code, don't mind me 😄 

---

> Thanks again and please let us know if there's anything else that we're missing!

I"m making one minor change there, and I'll happily merge it :) Thanks for doing this, once again!

**Pull request merged**
