### PR TITLE
Fix nearest neighbor index errors/Remove SciPy upper limit

### LINKED ISSUE #2474: Remove upper limit on version of SciPy and fix resulting test failures
In #2472, updating to `scipy == 1.12.0` led to four new errors in `test_grids.py`.  I'm not sure what the cause is, but it'd be worth reading through the [release notes for SciPy 1.12.0](https://docs.scipy.org/doc/scipy/release/1.12.0-notes.html).  It'd be really helpful to get this fixed before releasing `2024.1.0` next week.  

The errors are:

```
__________________________________ test_nonuniform_cartesian_NN_interp[pos0-quantities0-expected0] __________________________________
tests/test_grids.py:710: in test_nonuniform_cartesian_NN_interp
pout = nonuniform_cartesian_grid.nearest_neighbor_interpolator(pos, *quantities)
../utils/decorators/helpers.py:58: in wrapper
return f(*bound_args.args, **bound_args.kwargs)
grids.py:1423: in nearest_neighbor_interpolator
vals = self._interp_quantities[i, :]
E   IndexError: arrays used as indices must be of integer (or boolean) type
__________________________________ test_nonuniform_cartesian_NN_interp[pos1-quantities1-expected1] __________________________________
tests/test_grids.py:710: in test_nonuniform_cartesian_NN_interp
pout = nonuniform_cartesian_grid.nearest_neighbor_interpolator(pos, *quantities)
../utils/decorators/helpers.py:58: in wrapper
return f(*bound_args.args, **bound_args.kwargs)
grids.py:1423: in nearest_neighbor_interpolator
vals = self._interp_quantities[i, :]
E   IndexError: arrays used as indices must be of integer (or boolean) type
__________________________________ test_nonuniform_cartesian_NN_interp[pos2-quantities2-expected2] __________________________________
tests/test_grids.py:710: in test_nonuniform_cartesian_NN_interp
pout = nonuniform_cartesian_grid.nearest_neighbor_interpolator(pos, *quantities)
../utils/decorators/helpers.py:58: in wrapper
return f(*bound_args.args, **bound_args.kwargs)
grids.py:1423: in nearest_neighbor_interpolator
vals = self._interp_quantities[i, :]
E   IndexError: arrays used as indices must be of integer (or boolean) type
______________________________________ test_nonuniform_cartesian_nearest_neighbor_interpolator ______________________________________
tests/test_grids.py:736: in test_nonuniform_cartesian_nearest_neighbor_interpolator
pout = grid.nearest_neighbor_interpolator(pos, "x", persistent=True)
../utils/decorators/helpers.py:58: in wrapper
return f(*bound_args.args, **bound_args.kwargs)
grids.py:1423: in nearest_neighbor_interpolator
vals = self._interp_quantities[i, :]
E   IndexError: arrays used as indices must be of integer (or boolean) type
```

### PR DESCRIPTION
**Pull request by JaydenR2305**
An update to SciPy 1.12.0 conducted in #2472 revealed breaking changes made to SciPy's ``NearestNDInterpolator``.

The problematic lines can be seen here:
https://github.com/PlasmaPy/PlasmaPy/blob/d23a9a1140353189c4d3735e6fdad1e3272d564f/plasmapy/plasma/grids.py#L1388-L1398

The issue is that SciPy implicitly converts the grid indices (``indgrid``) to floats in the interpolation step. This is problematic because the return from this interpolation is used to index the quantity array:
https://github.com/PlasmaPy/PlasmaPy/blob/d23a9a1140353189c4d3735e6fdad1e3272d564f/plasmapy/plasma/grids.py#L1421-L1423

I propose we move the quantities array directly to the instantiation of the ``NearestNDInterpolator`` object, as seen in this PR:
https://github.com/PlasmaPy/PlasmaPy/blob/8ae396609efaddd428d28a8e639e91302f0b4e64/plasmapy/plasma/grids.py#L1388-L1398

Resolves #2474

### CODE REVIEW

**Comment by JaydenR2305** [comment]
@pheuer wanted me to make sure that we aren't doing multiple interpolations due to the nature of providing a multidimensional array for the data values in the construction of the ``NearestNDInterpolator``.

Here is the relevant code:
https://github.com/scipy/scipy/blob/4edfcaa3ce8a387450b6efce968572def71be089/scipy/interpolate/_ndgriddata.py#L144-L166

The underlying type/shape of the provided data values is actually _irrelevant_ until it comes to populating the ``interp_values`` array (at which point it is necessary to cast the array to the proper type, which isn't necessary in our case because we still use float64 as opposed to complex numbers.)

**Comment by pheuer** [comment]
> The underlying type/shape of the provided data values is actually _irrelevant_ until it comes to populating the `interp_values` array (at which point it is necessary to cast the array to the proper type, which isn't necessary in our case because we still use float64 as opposed to complex numbers.)

Sounds good, thanks for checking this - once you add a changelog entry I think we can merge this PR

**Comment by JaydenR2305** [comment]
oops forgot thanks for reminding me

**Review by StanczakDominik — APPROVED** [review]

**Comment by pheuer** [comment]
Thanks @StanczakDominik !

**Comment by namurphy** [comment]
Thank you for fixing and reviewing this so quickly!

**Pull request merged**
