### PR TITLE
Added axis labels to ITER parameters plots; Fixing #428

### LINKED ISSUE #428: add axis labels to ITER parameters plot
The ITER parameters plot [here](http://docs.plasmapy.org/en/stable/auto_examples/plot_physics.html#sphx-glr-auto-examples-plot-physics-py) could use some labels and units in said labels.

### PR DESCRIPTION
**Pull request by manasbedmutha98**
Adds axis labels to the plot of Langmuir Plasma Frequency vs Electron Concentration. Will fix #428

### CODE REVIEW

**Comment by manasbedmutha98** [comment]
@lemmatum and @StanczakDominik ; I'm new to open source and I'm sorry I've mixed things up. #428 and #277  were two separate issues. I'm not sure how to fix it. Please let me know what is to be done.

**Comment by StanczakDominik** [comment]
Haha, don't worry! For now, simply do whatever you want to do with the plot here and we'll merge both changes via this PR.

For the next time, try to create a feature branch to work on - you could then have a single branch for online help and another one for the plot labels. There's plenty of tutorials on that online. But for now, just don't worry about it for this PR :) Thanks for working on this, I'll look at it a bit later.

**Comment by StanczakDominik** [comment]
note to self: merge into stable

**Comment by StanczakDominik** [comment]
Merged, thanks @manasbedmutha98 !

**Pull request merged**
