### PR TITLE
CI fixes

### PR DESCRIPTION
**Pull request by StanczakDominik**
Fixes recent mishaps with CI on master

### CODE REVIEW

**Comment by StanczakDominik** [comment]
Thanks @rocco8773 for the hint!	

Looks like this works; I'll just merge it :)

**Comment by StanczakDominik** [comment]
Since this didn't fix things and now I'm getting unhashable type errors, I think it'll be simpler to close this and get #1105 through quickly, instead.

**Comment by StanczakDominik** [comment]
Nope, still no progress.

**Review by namurphy — APPROVED** [review]

**Comment by StanczakDominik** [comment]
Gotcha. Will make an issue on figuring out why sphinx 4.0 fails in a bit. For now, let's merge this - thanks @namurphy!

**Pull request merged**
