### PR TITLE
Changed subpackage name from analytic to math

### PR DESCRIPTION
**Pull request by LudovicoGitHub**
Modified some __init__.py functions to reflect that as well as test_dispersion.py. I also changed analytic.py to math.py.
If there is any problem let me know, I'll fix my mistakes :).

### CODE REVIEW

**Comment by StanczakDominik** [comment]
Hey, the build errored as you changed the filenames but forgot to change them in imports, so the code is looking for a now missing ` analytics` file. Please take a look at the Travis build and go through them - there's not too many!

PyCharm is a neat IDE that does this kind of thing semi-automatically, by the way.

**Comment by LudovicoGitHub** [comment]
I will look into it as soon as possible. Thank you for the patience!

**Comment by StanczakDominik** [comment]
Sure, there's no rush so take your time :)

12.09.2017 11:58 "LudovicoGitHub" <notifications@github.com> napisał(a):

**Comment by LudovicoGitHub** [comment]
I pushed my new changed files. Is the pull request updated with them? I think so, because I see that alla checks have passed now. 
Let me know if there is something more that I need to add, otherwise I think that this issues is solved now.

**Comment by namurphy** [comment]
@LudovicoGitHub - Thank you!  This looks good and I think you covered everything so I'll merge it shortly.  

This reminds me - I will need to change the "Analytic" label on GitHub to "Math" as well.  And probably create a new one for "Plasma parameters" since that used to be lumped in with "Analytic".  

@StanczakDominik - I heard good things about PyCharm at the SciPy 2017 conference, so I really should check that out too!  (Realistically though, it will probably be decades before I give up [emacs](https://xkcd.com/378/)....)

**Pull request merged**
