### PR TITLE
Tweaked add__magnetostatics

### PR DESCRIPTION
**Pull request by adityamagarde**
Moved the itertools out of the mstat for loop, so it's calculated only once instead of being calculated for every mstat.

I tested that function with a timer; the changed function takes lesser time.

Thank you for contributing to PlasmaPy!  Please check out our development guide at:

http://docs.plasmapy.org/en/master/development/index.html

Here are a few things to keep in mind when making a pull request (PR).

* Tests and docstrings are required for new or changed functionality.
* Please take care to write helpful commit messages: https://chris.beams.io/posts/git-commit/
* As a PR nears completion, fellow developers will likely suggest changes
  to be made before the PR is merged.
* Every pull request should include a changelog entry. Please see
  `changelog/README.rst` for instructions.
* PlasmaPy follows the PEP 8 style guide: https://www.python.org/dev/peps/pep-0008
* Please double check that a new PR will not duplicate an existing PR.
* If this PR will solve an issue tracked by GitHub, please add a phrase like
  "Closes #404." to automatically close the issue once the pull request is
  merged.  If your PR will not completely solve the issue, please still
  reference the issue.
* If this is your first contribution, please add your name to the author
  list in `docs/about/credits.rst`.
* Feel free to chat with other developers on our Matrix channel at:
  https://riot.im/app/#/room/#plasmapy:matrix.org

### CODE REVIEW

**Comment by StanczakDominik** [comment]
That's... yeah. That looks pretty obvious in retrospect :D I was too focused on using numba or numpy broadcasting to notive that. My bad.

Could you add a changelog entry and add yourself to the list of contributors in `docs/about/credits.rst`, if you'd like to be mentioned in there?

**Comment by StanczakDominik** [comment]
Also, before, `pytest -k magnetostatics`:

```
============================================================ 16 passed, 2686 deselected in 49.66s ============================================================
```
After:
```
============================================================ 16 passed, 2686 deselected in 3.03s =============================================================
```

**Comment by adityamagarde** [comment]
Hello Dominik, glad I could help.

Can you suggest me the pull request type? Also, I'm to opensource so I got a doubt. Should I make these changes and then do another pull request?

Thank you.

**Comment by adityamagarde** [comment]
Hi Dominik, I added the files in changelog folder.

**Comment by StanczakDominik** [comment]
Hey, I took the liberty of changing the changelog entry a bit, so it's more descriptive of why it's such an awesome change!

Merging it now! :)

**Pull request merged**
