### PR TITLE
Changed all 'checks_on_return' to 'validates_on_return'(only changed …

### PR DESCRIPTION
**Pull request by ShelleySugiharto**
…on docstring, did not touch raised error conflicts for accidental use of checks_on_return)

### CODE REVIEW

**Comment by ShelleySugiharto** [comment]
fixes #2788

**Comment by ShelleySugiharto** [comment]
pre-commit.ci autofix

**Comment by Stray235** [comment]
Closes #2788

**Comment by Stray235** [comment]
Closes #2788

**Review by namurphy — APPROVED** [review]
Looks good to me!  Thank you for doing this!

**Pull request merged**
