### PR TITLE
Replace @u.quantity_input with @validate_quantities

### LINKED ISSUE #880: Replace all uses of quantity_input with validate_quantites
There is still some functionality decorated with `@u.quantity_input` that should be decorated with `@validate_quantities` instead.

### PR DESCRIPTION
**Pull request by wskinner74**
- [x] I have added a changelog entry for this pull request.

- [ ] If adding new functionality, I have added tests and
      docstrings.

- [x] I have fixed any newly failing tests.

Fixes #880 

I changed all instances of `@u.quantity_input` with `@validate_quantities` as well as imported the module for `validate_quantities`. I am hoping this should work to fix the issue, please let me know if more work is needed. Thanks!

### CODE REVIEW

**Comment by wskinner74** [comment]
Looks like the isort test under style/pre-commit failed. Am I correct in assuming that's from leaving a blank line before the added imports?

**Review by wskinner74 — COMMENTED** [review]
Changed changelog file name to reflect correct PR number

**Review by wskinner74 — COMMENTED** [review]
Removed blank line from each added import to hopefully pass the isort test.

Edit: still not passing the isort test, any ideas for what I might be doing wrong?

**Comment by StanczakDominik** [comment]
isort also lets you apply its suggestions if you run it locally. We should probably state that more visibly somehow...

To apply the full linter suite, use `pre-commit run --all` :)

Make sure you pull the commit I added that does that for you!

**Comment by wskinner74** [comment]
@StanczakDominik oof, I completely missed that, thank you for applying that!

**Comment by wskinner74** [comment]
Thanks for all the help! I'm still a little rusty, so I apologize for the mess of commits in this PR :)

Is there anything else I need to do?

**Review by StanczakDominik — APPROVED** [review]
Looks good to me :+1:

And we're not even in triple digits for the number of commits, so don't worry about it ;)

Thanks for dealing with this one!

**Pull request merged**
