### PR TITLE
Add restructuredtext reference to documentation guide

### LINKED ISSUE #904: Link to a primer on restructuredtext in development guide
This can go in the documentation guide, probably.

### PR DESCRIPTION
**Pull request by Tiger-Du**
- [ ] I have added a changelog entry for this pull request.

- [ ] If adding new functionality, I have added tests and
      docstrings.

- [ ] I have fixed any newly failing tests.

Closes #904\.

1: Added a hyperlink to a primer on reStructuredText.
2-A: Replaced the link to the "numpydoc standard for docstrings".
2-B: Extended the anchor text of the hyperlink to include "standard for docstrings" to indicate that its destination is specific to the numpydoc standard for docstrings rather than numpydoc.

### CODE REVIEW

**Review by namurphy — APPROVED** [review]
Looks good — thank you for working on this!

**Comment by namurphy** [comment]
Also, would you like to add your name (and GitHub link) to the list of PlasmaPy contributors?  It's at [`docs/about/credits.rst`](https://github.com/PlasmaPy/PlasmaPy/blob/master/docs/about/credits.rst).

**Comment by Tiger-Du** [comment]
@namurphy -- Yes, I'd be happy to. Sorry for the delay!

**Review by namurphy — APPROVED** [review]

**Comment by namurphy** [comment]
@Tiger-Du — thank you for the contribution!

**Pull request merged**
