### PR TITLE
Update pinned requirements and fix errors associated with NumPy 1.24

### PR DESCRIPTION
**Pull request by namurphy**
I noticed after updating requirements in #2080 that we started getting a failure from null point functionality.  This was probably related to the release of NumPy 1.24.  Updating the requirements here was able to reproduce the error, which I will fix when I have a chance to look into it.

### CODE REVIEW

**Comment by namurphy** [comment]
I couldn't figure out what's happening with the newly failing tests, so I marked them as xfail.

**Comment by namurphy** [comment]
And now the Read the Docs builds are failing.  😿

**Comment by namurphy** [comment]
The RTD failure is completely unrelated to this pull request, and I'm attempting to address it in #2103.

**Review by ejohnson-96 — APPROVED** [review]
👍

**Pull request merged**
