### PR TITLE
Move coveragerc to default location

### PR DESCRIPTION
**Pull request by ritiek**
It looks like `coverage` isn't reading our [coveragerc](https://github.com/PlasmaPy/PlasmaPy/blob/27bfbed4c5d70395c0656051bfa1ac1a49ee2288/plasmapy/tests/coveragerc). This is a weird workaround that seems to work.

I moved `PlasmaPy/plasmapy/tests/coveragerc` to `PlasmaPy/.coveragerc` (default location expected by `coverage`) and created an empty file `PlasmaPy/plasmapy/tests/coveragerc` (without this empty file, there was an error complaining https://github.com/PlasmaPy/PlasmaPy/pull/496#issuecomment-396878676) and looks like it works.

Also see #495, #496, #497.

### CODE REVIEW

**Comment by Cadair** [comment]
Does this work locally with `python setup.py test --coverage`? I would expect it not to.

**Comment by ritiek** [comment]
@Cadair I think it does. I'll check it out real quick and report back.

**Comment by ritiek** [comment]
I tried it out locally and took a quick look in tested scripts, it does seem to be reading `exclude_lines` stuff now.
<details>
```
Name                                       Stmts   Miss  Cover   Missing                                                                                          [6/1341]
------------------------------------------------------------------------
plasmapy/__init__.py                          24      7    71%   24, 48-57
plasmapy/_base_init.py                        36     12    67%   13, 46-59
plasmapy/atomic/__init__.py                   13      0   100%
plasmapy/atomic/atomic.py                    150     10    93%   465, 895-898, 950, 1006, 1062, 1116, 1133
plasmapy/atomic/elements.py                    6      0   100%
plasmapy/atomic/isotopes.py                    2      0   100%
plasmapy/atomic/nuclear.py                    88      1    99%   264
plasmapy/atomic/parsing.py                   186      0   100%
plasmapy/atomic/particle_class.py            299      1    99%   559
plasmapy/atomic/particle_input.py            117      0   100%
plasmapy/atomic/special_particles.py         115      0   100%
plasmapy/atomic/symbols.py                    18      0   100%
plasmapy/classes/__init__.py                   4      0   100%
plasmapy/classes/plasma_base.py               31     10    68%   37, 41, 45, 49, 53, 68, 71, 74, 77, 80
plasmapy/classes/plasma_factory.py             9      0   100%
plasmapy/classes/sources/__init__.py           2      0   100%
plasmapy/classes/sources/plasma3d.py          42      0   100%
plasmapy/classes/sources/plasmablob.py        55      0   100%
plasmapy/classes/species.py                   56      0   100%
plasmapy/conftest.py                           3      0   100%
plasmapy/constants/__init__.py                10      0   100%
plasmapy/cython_version.py                     1      0   100%
plasmapy/diagnostics/__init__.py               0      0   100%
plasmapy/diagnostics/langmuir.py             207     27    87%   35, 109-111, 139, 145, 148, 151, 156, 382, 475, 1093, 1191-1228
plasmapy/import_helpers.py                    28     20    29%   14, 22-38, 47-54
plasmapy/io/__init__.py                        0      0   100%
plasmapy/mathematics/__init__.py               1      0   100%
plasmapy/mathematics/mathematics.py           38      0   100%
plasmapy/physics/__init__.py                   7      0   100%
plasmapy/physics/dielectric.py                23      0   100%
plasmapy/physics/dimensionless.py             15      0   100%
plasmapy/physics/distribution.py             194      0   100%
plasmapy/physics/magnetostatics.py           116      0   100%
plasmapy/physics/parameters.py               170      2    99%   1007-1008
plasmapy/physics/quantum.py                   73      0   100%
plasmapy/physics/relativity.py                20      0   100%
plasmapy/physics/transport/__init__.py         2      0   100%
plasmapy/physics/transport/braginskii.py     693      0   100%
plasmapy/physics/transport/collisions.py     215      2    99%   279, 1789
plasmapy/utils/__init__.py                     3      0   100%
plasmapy/utils/checks.py                     115      1    99%   300
plasmapy/utils/datatype_factory_base.py       49      0   100%
plasmapy/utils/exceptions.py                  33      0   100%
plasmapy/utils/pytest_helpers.py             241     23    90%   94, 115, 118, 143-144, 155-156, 183, 347, 376, 429-430, 519, 613, 652-653, 661, 671, 673, 675, 678, 687-688
plasmapy/visualization/__init__.py             0      0   100%
------------------------------------------------------------------------
TOTAL                                       3510    116    97%
```
</details>

**Comment by StanczakDominik** [comment]
Groan. I tried to do this with links and that crashed and burned. I'm just going to merge this and shed a single tear upon this workaround.

Now, to write an issue over at AstroPy...

**Pull request merged**
