### PR TITLE
Re-write 'Test independence and parametrization' section of testing guide

### PR DESCRIPTION
**Pull request by shaunagm**
## Description

This PR re-writes the [Test independence and parametrization](https://docs.plasmapy.org/en/latest/contributing/testing_guide.html#test-independence-and-parametrization) section of the testing guide to use extremely simple math.

## Motivation and context

I re-wrote the example math in this section to minimize cognitive load for the reader. This way they only need to think about the concept being taught, rather than also trying to remember the example math.

### CODE REVIEW

**Comment by shaunagm** [comment]
Hi @namurphy - not sure how to handle the codecov and pre-commit failures, the details are not informative enough for me to fix whatever needs fixing. (I do not have pre-commit hooks set up, which may be part of that particular failure.) Please let me know how to proceed, but otherwise I think everything should be good.

**Review by namurphy — COMMENTED** [review]
🎉 Thank you, @shaunagm!  It will helpful to have a description of test parametrization based on simpler math. I have two pretty minor suggestions and then we'll be just about ready to merge it.

✅ We can address the pre-commit failures by commenting on this PR with "pre-commit.ci autofix". 

👀 The Codecov failure is unrelated so we don't need to worry about that (#2757). 

Thank you again! 🙏🏻

**Comment by shaunagm** [comment]
Made the changes you suggested. Does "pre-commit.ci autofix" need to be in a separate comment or was your original comment enough? (I believe that would make it a [speech act](https://en.wikipedia.org/wiki/Speech_act) or whatever the written equivalent is)

**Comment by namurphy** [comment]
> Made the changes you suggested. Does "pre-commit.ci autofix" need to be in a separate comment or was your original comment enough? (I believe that would make it a [speech act](https://en.wikipedia.org/wiki/Speech_act) or whatever the written equivalent is)

Correct, "pre-commit.ci autofix" would need to be in a separate standalone comment.  And thanks!

**Comment by shaunagm** [comment]
pre-commit.ci autofix

**Review by namurphy — APPROVED** [review]
LGTM! 🚀 Thank you for doing this! 🙏🏻

**Pull request merged**
