### PR TITLE
[WIP] #bugpatch

### LINKED ISSUE #417: patches for v0.1.1
#bugpatch

In particular I think `setup.py` and cython integration need to be cleaned up.

### LINKED ISSUE #418: Integrate cython into release
There were some issues with numpy imports and whatnot... perhaps [these instructions](https://astropy.readthedocs.io/en/v0.2.3/development/building_packaging.html) will be useful for fixing issues with cython.

I believe all the cython stuff is currently removed for 0.1.0. Related to #417

### PR DESCRIPTION
**Pull request by StanczakDominik**
Closes #417 
Closes #418

### CODE REVIEW

**Comment by namurphy** [comment]
Do you think this PR would be a good place to raise the minimum required Cython version to ~0.27.2?  I remember there being a problem with installing the package with old versions of Cython like 0.27 or maybe 0.27.1 due to some Cython bugs.

**Comment by StanczakDominik** [comment]
So... Cython works, but:
```python
>>> parameters_cython.thermal_speed(5*u.eV, 'p')
   ...
TypeError: only dimensionless scalar quantities can be converted to Python scalars
>>> parameters_cython.thermal_speed(5, 'p')
287.30466431576656
>>> parameters_cython.thermal_speed(5.0, 'p')
287.30466431576656
```
that implementation doesn't take astropy units precisely because of the static typing. We'll have to think about it later, but it seems out of scope for this PR.

I remember wanting to do something more for this one...

**Comment by lemmatum** [comment]
Nice! And yes definitely make that a separate issue.

**Comment by StanczakDominik** [comment]
Okay, I guess I'll merge this now.

**Pull request merged**
