### PR TITLE
Issue 2673: Rename `binding_energy` to remove ambiguity, add `electron_binding_energy`

### PR DESCRIPTION
**Pull request by chasepd**
## Description

Adds requested feature from https://github.com/PlasmaPy/PlasmaPy/issues/2673.

- Renames `binding_energy` to `nuclear_binding_energy`, but leaves `binding_energy` as a pointer to `nuclear_binding_energy` for backwards compatibility with a warning that it is deprecated and will be removed in a future release.
- Adds `electron_binding_energy`, defined as the sum of `ionization_energy` for all charge states above the given ionization. 

## Motivation and context

See https://github.com/PlasmaPy/PlasmaPy/issues/2673. With the addition of ionization energy data, calculating `electron_binding_data` becomes fairly easy. However, this causes `binding_energy` to be ambiguous/confusing, and is renamed to `nuclear_binding_energy` for clarity and greater specificity.

## Related issues

Resolves https://github.com/PlasmaPy/PlasmaPy/issues/2673.

### CODE REVIEW

**Comment by chasepd** [comment]
@pheuer - here's a new PR from a fresh branch!

**Comment by pheuer** [comment]
> @pheuer - here's a new PR from a fresh branch!

Thank you!!! Here's a couple comments: 

1) Can you make it work for isotopes, similar to the `ionization_energy` property? E.g. 

```python
Particle("C +3").electron_binding_energy == Particle("C-12+3").electron_binding_energy
>True
```
Again, should work for everything above hydrogen, but return separate values for the hydrogen isotopes since the ionization energies are measurably different there. 

2) I think you might be adding one too few ionization energies onto the list? 

```python
Particle("C +3").electron_binding_energy.to(u.eV) 
> 882.08 eV 
```

But according to the NIST database, that's the ionization energy of C+4, and C+3 should be `946.57 eV`. Binding energy being the energy required to free every electron the ion has. This is a little confusing, so maybe you could clarify conceptually a bit in the docstring? 

Otherwise this looks great to me, thanks again for doing this!

**Comment by chasepd** [comment]
pre-commit.ci autofix

**Comment by chasepd** [comment]
@pheuer took me a bit to get back to this, but this should have those items fixed!

**Review by pheuer — APPROVED** [review]
@chasepd Awesome, this looks great, thanks for adding this feature!!

**Pull request merged**
