### PR TITLE
Fix Gilesbot settings

### PR DESCRIPTION
**Pull request by StanczakDominik**
This implements settings from https://github.com/Cadair/baldrick/blob/checks_towncrier/doc/plugins.rst

- [ ] I have added a changelog entry for this pull request (please see
  `changelog/README.rst` for instructions, and if you need help with picking the PR type, ask!)
- [ ] If adding new functionality, I have added (passing) tests and
      docstrings. (Tests pop up at the bottom, in the checks box).
- [ ] I have fixed any new failing tests (if you're unsure why
  they're failing, ask!).

### CODE REVIEW

**Comment by StanczakDominik** [comment]
Okay, I'm stumped - Gilesbot doesn't seem to react to my config changes much. @Cadair, halp?

**Comment by Cadair** [comment]
It will only read the config from the base branch (master) this is so that people can't reconfigure the bot by editing the config on their PR.

**Comment by StanczakDominik** [comment]
... that would explain it! In that case I'll merge it tomorrow, when I'm able to repair stuff if it breaks ASAP. Thanks for the explanation!

**Comment by StanczakDominik** [comment]
Well, I tested that using 3dd7838 in another pull request, and as seen at https://github.com/PlasmaPy/PlasmaPy/pull/712/checks?check_run_id=287980391, and clearly I'm still missing something - I expected the message at the bottom, in the checks box, to say "gilesbot:missing_file — Missing changelog entry", and it's still at "gilesbot:missing_file — gilesbot:missing_file".

**Pull request merged**
