### PR TITLE
Create notebook for observations of ionization states in the solar wind

### PR DESCRIPTION
**Pull request by namurphy**
The goal of this pull request is to create a notebook that uses `IonizationStateCollection` to visualize observations made by *Ulysses* in the solar wind.  My current plan is to base this off of the data from [Ko et al. (1999)](https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/1999JA900112), and compare ionization states of carbon, oxygen, iron, etc. in the slow solar wind to the fast solar wind, and include a discussion of the physics.  

I plan to use this as an example in the Python in Heliophysics Community (PyHC) [summer school](https://heliopython.org/summer-school) that's happening at the end of May, so I have a pretty well-defined due date. 😅

### CODE REVIEW

**Comment by namurphy** [comment]
Some of the work towards this was done while I was putting together the [PyHC tutorial for PlasmaPy](https://github.com/heliophysicsPy/summer-school/blob/8e084b3c335d0d2f0746b24c327de2b481abd167/plasmapy-tutorial/plasmapy-tutorial-instructor.ipynb).

Also it's now looking at ACE observations instead of Ulysses since I found a particularly interesting paper.

**Comment by StanczakDominik** [comment]
Any ideas for why [nothing is executed in the doc build for this notebook](https://plasmapy--1513.org.readthedocs.build/en/1513/notebooks/particles/ace.html)? Oh crud, actually I think I know. I think a partially executed notebook (note the first two cells) might still be treated as a pre-executed one!

**Review by StanczakDominik — COMMENTED** [review]
Any ideas for why [nothing is executed in the doc build for this notebook](https://plasmapy--1513.org.readthedocs.build/en/1513/notebooks/particles/ace.html)? Oh crud, actually I think I know. I think a partially executed notebook (note the first two cells) might still be treated as a pre-executed one! If we clear the outputs from all cells, it should be fine.

**Comment by namurphy** [comment]
Finally got back to this!  I added some broader information and plots today, and it looks like it's ready for review.  Here's a [preview of the notebook](https://plasmapy--1513.org.readthedocs.build/en/1513/notebooks/particles/ace.html) which looks like it's getting executed correctly now.  

I had been hoping to do a few other things, but rather than probably waiting for a couple of months, I'll likely create an issue or two on the following:

 - Use methods within `IonizationState` and `IonizationStateCollection` to plot the stuff near the end (depends on #579)
 - Add a thumbnail graphic
 - Use a Python in Heliophysics Community package (pySPEDAS, SpacePy, or pysat?) to download the data (which would probably necessitate pre-executing the notebook so that our CI doesn't end up having to download more data than it needs to...or maybe we could cache it?)

**Comment by StanczakDominik** [comment]
Yeah, preferably just pre-execute it. Simpler.

**Review by ejohnson-96 — APPROVED** [review]
👍 I like this notebook, useful introduction for people who might understand the science but not know how to use the functionality

**Pull request merged**
