### PR TITLE
Issue 2673: Rename `binding_energy` to remove ambiguity, add `electron_binding_energy` 

### PR DESCRIPTION
**Pull request by chasepd**
## Description

Adds requested feature from https://github.com/PlasmaPy/PlasmaPy/issues/2673.

- Renames `binding_energy` to `nuclear_binding_energy`, but leaves `binding_energy` as a pointer to `nuclear_binding_energy` for backwards compatibility with a warning that it is deprecated and will be removed in a future release.
- Adds `electron_binding_energy`, defined as the sum of `ionization_energy` for all charge states above the given ionization. 

## Motivation and context

See https://github.com/PlasmaPy/PlasmaPy/issues/2673. With the addition of ionization energy data, calculating `electron_binding_data` becomes fairly easy. However, this causes `binding_energy` to be ambiguous/confusing, and is renamed to `nuclear_binding_energy` for clarity and greater specificity.

## Related issues

Resolves https://github.com/PlasmaPy/PlasmaPy/issues/2673.

### CODE REVIEW

**Comment by chasepd** [comment]
pre-commit.ci autofix

**Comment by chasepd** [comment]
@pheuer - FYI since you submitted https://github.com/PlasmaPy/PlasmaPy/issues/2673

**Comment by pheuer** [comment]
@chasepd This looks great! 

Unfortunately something really strange is happening with Git here (probably my fault): when I tried to pull this branch locally, GitHub Desktop ended up pushing `chasepd/main` into this branch? And then when I tried to revert that, it doesn't seem to have worked?? @namurphy HELP! 

I think the issue might be that it looks like you are editing the code on your main branch, then opening PRs from that. Typically it's better to make a new branch for each PR (from main), then delete it after the PR is merged. Probably wouldn't be an issue if I was better at Git!

**Comment by chasepd** [comment]
> @chasepd This looks great!
> 
> Unfortunately something really strange is happening with Git here (probably my fault): when I tried to pull this branch locally, GitHub Desktop ended up pushing `chasepd/main` into this branch? Which is also `chasepd/main`? And then when I tried to revert that, it doesn't seem to have worked?? @namurphy HELP!
> 
> I think the issue might be that it looks like you are editing the code on your main branch, then opening PRs from that. Typically it's better to make a new branch for each PR (from main), then delete it after the PR is merged. Probably wouldn't be an issue if I was better at Git!
> 
> EDIT: Just to reassure you nothing is lost, I'm easily able to create a new branch off of your last commit, which I've done here: https://github.com/pheuer/PlasmaPy/tree/2657_save
> 
> I just can't figure out how to reset THIS branch. I think only you may be able to do that, since it is on your repository.

No worries! I have a local copy, I'll just nuke this PR and my local fork, re-fork this, and then make a new PR from a non-main branch

**Pull request closed without merging**
