### PR TITLE
Add examples to `thermal_bremsstrahlung` docstring

### LINKED ISSUE #2529: Add an examples section in the docstring for `thermal_bremsstrahlung`
[to be added]

### PR DESCRIPTION
**Pull request by jwreep**
## Description

I've added a few examples to the docstring of `thermal_bremsstrahlung`.

## Related issues

Fixes #2529

### CODE REVIEW

**Comment by pheuer** [comment]
> Not sure I understand the Read the Docs error in the checks. What have I done wrong here?

@namurphy  FYI
I'm looking into this: I can reproduce this error locally by upgrading my lmfit version from 1.2.0 to 1.3.0 (the latter is what PlasmaPy is now running on, at least in CI).  The error occurs in `thomson_fitting.ipynb`: 

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[9], line 2
      1 fit_kws = {}
----> 2 epw_result = epw_model.fit(
      3     epw_skw,
      4     params=params,
      5     wavelengths=epw_wavelengths.to(u.m).value,
      6     method="differential_evolution",
      7     fit_kws=fit_kws,
      8 )

File ~\anaconda3\envs\dev311\Lib\site-packages\lmfit\model.py:1174, in Model.fit(self, data, params, weights, method, iter_cb, scale_covar, verbose, fit_kws, nan_policy, calc_covar, max_nfev, coerce_farray, **kwargs)
   1168     fit_kws = {}
   1170 output = ModelResult(self, params, method=method, iter_cb=iter_cb,
   1171                      scale_covar=scale_covar, fcn_kws=kwargs,
   1172                      nan_policy=self.nan_policy, calc_covar=calc_covar,
   1173                      max_nfev=max_nfev, **fit_kws)
-> 1174 output.fit(data=data, weights=weights)
   1175 output.components = self.components
   1176 return output

File ~\anaconda3\envs\dev311\Lib\site-packages\lmfit\model.py:1559, in ModelResult.fit(self, data, params, weights, method, nan_policy, **kwargs)
   1557 self.userargs = (self.data, self.weights)
   1558 self.userkws.update(kwargs)
-> 1559 self.init_fit = self.model.eval(params=self.params, **self.userkws)
   1560 _ret = self.minimize(method=self.method)
   1561 self.model.post_fit(_ret)

File ~\anaconda3\envs\dev311\Lib\site-packages\lmfit\model.py:997, in Model.eval(self, params, **kwargs)
    964 def eval(self, params=None, **kwargs):
    965     """Evaluate the model with supplied parameters and keyword arguments.
    966 
    967     Parameters
   (...)
    995 
    996     """
--> 997     return coerce_arraylike(self.func(**self.make_funcargs(params, kwargs)))

File ~\GitHub\PlasmaPy\plasmapy\diagnostics\thomson.py:685, in _spectral_density_model(wavelengths, settings, **params)
    678 """
    679 lmfit Model function for fitting Thomson spectra.
    680 
    681 For descriptions of arguments, see the `thomson_model` function.
    682 """
    684 # LOAD FROM SETTINGS
--> 685 ion_z = settings["ion_z"]
    686 ion_mass = settings["ion_mass"]
    687 probe_vec = settings["probe_vec"]

TypeError: 'NoneType' object is not subscriptable
```

**Comment by jwreep** [comment]
Well, at least glad to hear it wasn't something I did.  I was a bit surprised that adding comments should cause issues.

Thanks for diagnosing the error!

**Comment by pheuer** [comment]
> Well, at least glad to hear it wasn't something I did. I was a bit surprised that adding comments should cause issues.
> 
> Thanks for diagnosing the error!

Thanks for finding it! A fix has now been merged into main, so if you merge main into this branch this test should pass!

**Comment by jwreep** [comment]
Well, readthedocs passed, but looks like another bug has taken its place.  Has anything else been patched?

```
FAILED plasmapy/utils/data/tests/test_downloader.py::test_at_most_one_api_call - requ...
FAILED plasmapy/utils/data/tests/test_downloader.py::test_creating_another_downloader
```

**Comment by pheuer** [comment]
This test that failed relies on a connection to the GitHub API, and for some reason it looks like that is timing out? I wonder if the API is just temporarily down? I am trying re-running it 

```
======================================= FAILURES =======================================
______________________________ test_at_most_one_api_call _______________________________
[gw2] darwin -- Python 3.11.8 /Users/runner/work/PlasmaPy/PlasmaPy/.tox/py311-pins-pytest_cov_all/.venv/bin/python
.tox/py311-pins-pytest_cov_all/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:467: in _make_request
    self._validate_conn(conn)
.tox/py311-pins-pytest_cov_all/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: in _validate_conn
    conn.connect()
.tox/py311-pins-pytest_cov_all/.venv/lib/python3.11/site-packages/urllib3/connection.py:653: in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
.tox/py311-pins-pytest_cov_all/.venv/lib/python3.11/site-packages/urllib3/connection.py:806: in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
.tox/py311-pins-pytest_cov_all/.venv/lib/python3.11/site-packages/urllib3/util/ssl_.py:465: in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
.tox/py311-pins-pytest_cov_all/.venv/lib/python3.11/site-packages/urllib3/util/ssl_.py:509: in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py:517: in wrap_socket
    return self.sslsocket_class._create(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py:1104: in _create
    self.do_handshake()
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py:1382: in do_handshake
    self._sslobj.do_handshake()
E   TimeoutError: _ssl.c:9[89](https://github.com/PlasmaPy/PlasmaPy/actions/runs/8577281504/job/23509646075?pr=2618#step:6:90): The handshake operation timed out
```

**Comment by pheuer** [comment]
Ok, re-running that test fixed it, so I think it was just a communication issue with the API 

@namurphy it looks like the codecov error is rearing it's head again, even after I think #2624 was merged into this branch? 

```
Run codecov/codecov-action@v4
==> macos OS detected
https://cli.codecov.io/latest/macos/codecov.SHA256SUM
==> Running version latest
==> Running version v0.4.9
==> Running git config --global --add safe.directory /Users/runner/work/PlasmaPy/PlasmaPy
/usr/local/bin/git config --global --add safe.directory /Users/runner/work/PlasmaPy/PlasmaPy
==> Running command '/Users/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit'
/Users/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit --git-service github -C b61ba8817d6e7f1656a28f79cd6d4876a46745b3 -Z
info - 2024-04-06 01:24:41,896 -- ci service found: github-actions
gpg: directory '/Users/runner/.gnupg' created
gpg: /Users/runner/.gnupg/trustdb.gpg: trustdb created
gpg: key 806BB28AED779869: public key "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1

gpg: Signature made Thu Mar 28 [15](https://github.com/PlasmaPy/PlasmaPy/actions/runs/8577281504/job/23510545977?pr=2618#step:7:16):15:56 2024 UTC
gpg:                using RSA key 27034E7FDB850E0BBC2C62FF806BB28AED779869
gpg: Good signature from "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2703 4E7F DB85 0E0B BC2C  62FF 806B B28A ED77 9869

Error: Codecov token not found. Please provide Codecov token with -t flag.
==> Uploader SHASUM verified (cb250ac4addcd9a[21](https://github.com/PlasmaPy/PlasmaPy/actions/runs/8577281504/job/23510545977?pr=2618#step:7:22)bf1c73d583cdae0e7fbd2c369350829fcc21ffb55ca81e6  codecov)
```

**Review by namurphy — APPROVED** [review]
LGTM! 👍🏻 Thank you again for doing this, and for your patience while we fixed some of our continuous integration checks!  Happy to merge it now that we got the stuff that broke figured out.

**Pull request merged**
