### PR TITLE
Raise ValueError for implicit cases in `distribution`

### LINKED ISSUE #2221: Address functions in `distributions.py` with unexpected possible `return None`
While working on #2213, I noticed that there were a few functions in `distributions.py` which had an implicit `return None` that should not be possible.  We should update these functions so that an exception is raised instead of `None` being returned.

We'll need to check #2213 to see all of the functions.  (If I have time and the wherewithal, I'll make this update later.)

### PR DESCRIPTION
**Pull request by JaydenR2305**
Resolves #2221

### CODE REVIEW

**Comment by pheuer** [comment]
Any idea why CodeCov thinks the exception lines aren't being covered? It looks to me like you wrote tests for them...

**Comment by JaydenR2305** [comment]
> Any idea why CodeCov thinks the exception lines aren't being covered? It looks to me like you wrote tests for them...

No idea...

**Comment by JaydenR2305** [comment]
Fixed it!

**Review by pheuer — APPROVED** [review]
LGTM, thanks Jayden! (merge when ready)

**Pull request merged**
