### PR TITLE
Example jupyter notebooks

### PR DESCRIPTION
**Pull request by StanczakDominik**
As discussed today at telecon, I'm starting to work on a bunch of notebooks illustrating what's possible with PlasmaPy.

For now, we have a first pass at analytic functions, as `ls` outputs the directories sorted by name, and that sort of... happened.

### CODE REVIEW

**Comment by StanczakDominik** [comment]
@namurphy here's a very first pass on the `atomic` functionality!

**Comment by namurphy** [comment]
The error when running `half_life('U-238')` occurs because only a fraction of the available isotopes have half-life data since I had trouble finding a good machine-readable table of nuclide half-lives when I was generating the dictionary for isotopes.  I raised this in #105.  For the moment, perhaps we can change it to `half-life('T')`.

Thank you for working on this!

**Comment by StanczakDominik** [comment]
Right, I thought I had seen this raised somewhere. Thanks for the reminder!

I'll try to keep working on this tomorrow or sometime later this week. If
you have any suggestions for content, just leave it here!

19.09.2017 22:51 "Nick Murphy" <notifications@github.com> napisał(a):

**Comment by Cadair** [comment]
I would recommend looking into sphinx-gallery and not directly version controlling jupyter notebooks. (We did this experiment with sunpy.)

**Comment by StanczakDominik** [comment]
https://sphinx-gallery.readthedocs.io/en/latest/getting_started.html leaving this here as a note to self

**Comment by StanczakDominik** [comment]
https://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py Here's another thing that looks really handy.

**Comment by StanczakDominik** [comment]
Gentlepeople, the Sphinx Gallery example page is available here:

http://plasmapy-stanczakdominik-test.readthedocs.io/en/jupyter/auto_examples/

**Comment by StanczakDominik** [comment]
So I've got it working kinda nicely, what remains to be done is to adapt the examples we have to the new format and then I'll be merging this, I think.

I'd also like to find a way to automatically report whether the examples are building, as a third check alongside Travis and Coveralls.

**Comment by dstansby** [comment]
You'll need to reabse on to master to pick up the new circleci config

**Comment by dstansby** [comment]
I'm also guessing you'll need to add `sphinx-gallery` to the doc-requirements file that I added to make the build work.

**Comment by StanczakDominik** [comment]
Yeah that was what I was going to try next, if not for my bus stop - which I managed not to miss this time, so that's a success!

Thanks for being a watchful guardian though :D

**Comment by StanczakDominik** [comment]
https://www.youtube.com/watch?v=AXwGVXD7qEQ

Thanks a lot, @dstansby !

**Comment by StanczakDominik** [comment]
I think I'd like to merge this sooner later than later. At this point the main functionality - sphinx gallery - is complete. What's left to be done is
* [ ] make docs for the new stuff - probably not *too* critical as the format can be mostly inferred from the existing working examples 
* [ ] update the examples we already had - doesn't impact other

I believe that it'd be better to merge this now and finish the above on the go, as this PR will start detecting which of our changes are breaking docs and thus will allow fixing them before more amass. Also, rebases (literally just `git rebase master`, then follow the instructions) of current branches on top of master will probably be necessary to get tests working as soon as possible. This may break them due to the added dependence on CircleCI.

**Comment by StanczakDominik** [comment]
Oh yeah, by the way, the `atomic` example is currently mostly commented out. That API volatility we were talking about @namurphy seems to have completely broken the previous example (understandable). I'll fix this later. The point about merging the core changes to doc builds still stands.

**Pull request merged**
