### PR TITLE
Lite-Functions Ep. 4 | permittivity_1D_Maxwellian

### PR DESCRIPTION
**Pull request by pheuer**
Creates a lite function version of the `permittivity_1D_Maxwellian` function, which is required for #974 

This PR depends on #1473 and should be merged after that PR is complete. 

This function internally calls `thermal_speed` and `plasma_frequency`. So, in the lite function we have a choice: 

- Take all the arguments for both of those functions, plus new ones for `permittivity_1D_Maxwellian`, and call the other lite functions inside `permittivity_1D_Maxwellian_lite`.

- Take `vTh` and `wp` as inputs, and require the lite function user to calculate them using their lite functions separately. 

I chose the second for a number of reasons 

- Minimizes the number of inputs and duplicated documentation. Otherwise we have to re-document every argument on this new lite function.
- Potentially more efficient: if the user has already calculated vTh and wp (as is indeed the case in the Thomson module) repeating the computation is wasteful. 
- This way the regular `permittivity_1D_Maxwellian` function still calls the regular `thermal_speed` and `plasma_frequency` functions, which means all of their input validation is being done as normal. 

The only downside is that, if a lite function user only wants `permittivity_1D_Maxwellian_lite`, they will have to explicitly call the functions it depends upon. But I don't think that's a big deal: they're a lite function user, so they should be willing to go through this extra bit of trouble for the sake of efficiency.

### CODE REVIEW

**Comment by pheuer** [comment]
This PR (and #1473 ) are ready to review. The failing changelog test here is an error, because I based this branch off of #1473 and so it's seeing that changelog entry.

**Comment by rocco8773** [comment]
> This PR (and #1473 ) are ready to review. The failing changelog test here is an error, because I based this branch off of #1473 and so it's seeing that changelog entry.
> 
> Edit: Does @namurphy or @StanczakDominik know a way to avoid this? Should I do something differently with the PR, or is this a bug with the changelog CI?

You don't need to worry about it right now.  It should resolve itself once PR #1473 is merged.  It's showing up in this PR right now because it is a change over the current `main` branch.

**Comment by rocco8773** [comment]
> This PR depends on #1473 and should be merged after that PR is complete.
> 
> This function internally calls `thermal_speed` and `plasma_frequency`. So, in the lite function we have a choice:
> 
>     * Take all the arguments for both of those functions, plus new ones for `permittivity_1D_Maxwellian`, and call the other lite functions inside `permittivity_1D_Maxwellian_lite`.
> 
>     * Take `vTh` and `wp` as inputs, and require the lite function user to calculate them using their lite functions separately.
> 
> 
> I chose the second for a number of reasons
> 
>     * Minimizes the number of inputs and duplicated documentation. Otherwise we have to re-document every argument on this new lite function.
> 
>     * Potentially more efficient: if the user has already calculated vTh and wp (as is indeed the case in the Thomson module) repeating the computation is wasteful.
> 
>     * This way the regular `permittivity_1D_Maxwellian` function still calls the regular `thermal_speed` and `plasma_frequency` functions, which means all of their input validation is being done as normal.

@namurphy Can I get your opinion on this?  I completely agree with @pheuer's points, but I can pull myself away from the position that the `lite` signature should be the same as the non-lite version and the arguments should be in the base parameters because that's the rule for the whole formulary.

**Review by rocco8773 — APPROVED** [review]
For expeditious reason I went ahead and made the changes I would have suggested.  All my comments would have been related to typos, PEP8 fixes, or the same type of suggestions I made in #1473.  Nothing too crazy.

**Review by rocco8773 — APPROVED** [review]

**Comment by pheuer** [comment]
Awesome  - thanks @rocco8773 !

**Pull request merged**
