### PR TITLE
Create plasmapy.dispersion & migrate current functionality

### PR DESCRIPTION
**Pull request by ahmadryan**
Created a new folder **dispersion** in Top-Level Sub-Packages. 

- [x] I have added a changelog entry for this pull request.

- [x] If adding new functionality, I have added tests and
      docstrings.

- [x] I have fixed any newly failing tests.

### CODE REVIEW

**Review by rocco8773 — CHANGES_REQUESTED** [review]
This is looking good!  I've done a combination of review requested changes and push my own changes to your branch.  I pushed changes related to dispersion documentation files `.rst` just because it would be too difficult to explain.  Take a look at what I did and let me know if you have any questions.

**Comment by ahmadryan** [comment]
> This is looking good! I've done a combination of review requested changes and push my own changes to your branch. I pushed changes related to dispersion documentation files `.rst` just because it would be too difficult to explain. Take a look at what I did and let me know if you have any questions.

So...now that I have accepted the changes and committed them, can we go ahead and merge the two branches?

**Comment by rocco8773** [comment]
@rocco8773 Ok, I'll review it and, if it looks good, I'll merge.

**Review by rocco8773 — APPROVED** [review]
Looks good to me! Thanks for doing this!

**Comment by rocco8773** [comment]
Closes #749

**Pull request merged**
