### PR TITLE
Two stages of tests

### PR DESCRIPTION
**Pull request by StanczakDominik**
What this does can be best seen in the [Checks tab](https://github.com/PlasmaPy/PlasmaPy/pull/1350/checks). I split tests into two groups, one happening after the other, and moved code coverage to a single run in the latter. If I got it right, the second stage should run conditionally on the first one (linters and one quick run of tests, except the slow ones), and codecov should only trigger once.

### CODE REVIEW

**Comment by StanczakDominik** [comment]
Also, seems like the minimal dependencies test was not actually running correctly: only now it started running in a single process context, raising the same issue as the recent https://github.com/conda-forge/plasmapy-feedstock/pull/16#issuecomment-983764940 . I have hopes for the rework in https://github.com/PlasmaPy/PlasmaPy/pull/1295 to fix that test.

Meanwhile `Python 3.8, slow tests with code coverage` is expected, but not coming, as it got renamed. `CI / Python 3.8, all tests, code coverage (pull_request)` is sort of doing the Faramir routine of not being exactly what the Steward expected, but still the next best thing.

**Comment by namurphy** [comment]
I'm liking this!  Some quick thoughts...

* It'd be helpful to have the `CI / Documentation (pull_request)` be one of the initial tests, especially for PRs that change the docs only.  
* Eventually I'd prefer the initial round of tests to be done with Python 3.10 because of [improvements with error messages](https://docs.python.org/3/whatsnew/3.10.html#better-error-messages).  But that's for another day.  

Many thanks!

**Comment by StanczakDominik** [comment]
> I'm liking this! Some quick thoughts...
> 
>     * It'd be helpful to have the `CI / Documentation (pull_request)` be one of the initial tests, especially for PRs that change the docs only.

I was hesitant to put those in there, because - if you take a look at the runtimes - the current Python3.9 tests and the linters run in one minute. The full test suites take 2-4 minutes, and the doc build takes five. Having it stall the full test suites seems meh.

Perhaps instead we could run it independently, completely in parallel, and together with linters? Does that sound better?

>     * Eventually I'd prefer the initial round of tests to be done with Python 3.10 because of [improvements with error messages](https://docs.python.org/3/whatsnew/3.10.html#better-error-messages).  But that's for another day.

I updated https://github.com/PlasmaPy/PlasmaPy/pull/1292/ to re-check whether it's still blowing up on us.

**Comment by namurphy** [comment]
> Perhaps instead we could run it independently, completely in parallel, and together with linters? Does that sound better?

Yes!  That's a great idea.

**Comment by StanczakDominik** [comment]
@namurphy does https://github.com/PlasmaPy/PlasmaPy/actions/runs/1579737561 look better, now? :)

**Review by namurphy — APPROVED** [review]
Yep, looks good to me!

**Pull request merged**
