### PR TITLE
Closes #128

### LINKED ISSUE #128: Automate testing of example code with doctest
Python's built-in [doctest](https://docs.python.org/3.6/library/doctest.html) module includes capabilities to search through docstrings for examples that look like interactive Python sessions, and then make sure that the actual output of the examples matches what is shown in the docstring example.  This capability should be included in our continuous integration testing so that we can ensure that our example code is accurate.  This testing is especially important prior to version 0.1 since our application program interface (API) within different subpackages is evolving from month to month.  We will probably need to implement this for docstrings as well as the documentation in our `docs` directory.  The`atomic` subpackage may be a good first place to test, since there were a few recent API changes and I might have missed updating some of the examples.

Thank you!
-Nick

### PR DESCRIPTION
**Pull request by pohzipohzi**
Closes #128.

### CODE REVIEW

**Comment by StanczakDominik** [comment]
I couldn't see the tests going through doctest via Travis, I'll run pytest with these changes from my PC and see what's up with it. If it works, I'll merge this straight away, if not, let's keep working on this one.

Thanks a bunch @pohzipohzi!

**Comment by StanczakDominik** [comment]
@pohzipohzi given you put `pytest.ini` inside `plasmapy`, I guess you were running `pytest` from inside `plasmapy`, right? Travis CI didn't register that, so the doctests didn't go through there. If you move  `pytest.ini` to Plasmapy root on your branch, it should detect your changes and the test results should be visible from [here](https://travis-ci.org/PlasmaPy/PlasmaPy/builds/281732428).

Once that's changed, I'm getting a bunch of doctest failures on the modified pytest run (actually I used `coverage run -m pytest plasmapy` as that's what's used for Coveralls). Could you look into that and try to remove whichever you can? I'll help along, so if you get any you don't feel like bothering with, leave them to me.

**Comment by pohzipohzi** [comment]
Hi @StanczakDominik.

Apologies, I wasn't familiar with travis, so I didn't test using the script indicated. Did you also mean that we change the script in travis to `coverage run -m pytest plasmapy`?

With regards to the errors, I managed to resolve a few minor ones. Quite a number of errors are precision-related (some I'm not sure though, see `debye_number`, or `ion_plasma_frequency`). I read that there was a change in the API recently, and I know nothing about physics, so I hope I don't have to touch those. Some other errors are more API related, such as `mass_number("N")` or `_check_quantity`.

Will also read up on fixing errors with decorators

**Comment by StanczakDominik** [comment]
Running pytest on the PlasmaPy code directory only seems to be a working solution, and as far as I know we're not committing any atrocities with that solution, so I'd be willing to go with it :) a second opinion wouldn't go amiss though. @SolarDrew?

As for the more physics-y errors, I'll fix them, so don't worry about it!

**Comment by StanczakDominik** [comment]
Upon some investigating, I think we could also use @namurphy 's input here... there's a bunch of wacky cases (see [here](https://travis-ci.org/PlasmaPy/PlasmaPy/builds/281878775?utm_source=github_status&utm_medium=notification)), as in:

- a lot of floating point calculations being off, which can probably be changed to fit with what's happening now but I'm not 100% sure about
- `ion_inertial_length(5*u.m**-3, ion='He+')` getting larger by a factor of 85
- `ion_gyrofrequency(0.01*u.T)` increasing by a factor of 2 pi (astropy conversions?) 
- the signature for the proton mass constant possibly changing in the new version of Astropy

**Comment by namurphy** [comment]
I though there was a good chance that I made a few mistakes on some of the examples, so I'm glad that doctest is catching them.  If you'd like, feel free to replace the broken examples with the actual output.  Or, if you'd prefer, I can do that later this week.  Thank you!

**Comment by StanczakDominik** [comment]
I'll get them done :)

**Comment by StanczakDominik** [comment]
Hey @pohzipohzi, I'm trying to push some of those doctest fixes and failing. Am I messing something up here, or did you perhaps not check the option to allow commits from maintainers? I don't know how to tell.

It should look like this in the sidebar to the right, at this page.

screenshot_20171003_081332

**Comment by pohzipohzi** [comment]
@StanczakDominik  that box is checked on my end

**Comment by StanczakDominik** [comment]
All right, please merge pohzipohzi/PlasmaPy#1 into your branch then :)

**Comment by StanczakDominik** [comment]
Oh yeah... pep8 would argue about that. Fixes in progress!

**Comment by StanczakDominik** [comment]
pohzipohzi/PlasmaPy#2 fixes the pep8 issues bar one, which I was unable to sensibly remove. Astropy exceptions are just long like that. I think we should let that one stay.

**Comment by StanczakDominik** [comment]
My bad, sorry, for the pull request spam @pohzipohzi, I forgot you have to use [personal access tokens](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) to push from command line when using two factor authentication.

Anyway, I think this is mergeable! Is everyone ok with a slight hit to coverage which I'm going to fix with #117 anyway?

---------

@namurphy I'd still appreciate your look at the changes in docstrings  if you can find the time. Some of those discrepancies are pretty huge, a bunch of them seeming to be a result of those Astropy radian conversions. Also, (though maybe this is fixed in master?) `mass_number('N')` has started failing with a `ValueError`.

I'll be doing some plotting for those functions in #115 this week. If there are any major bugs in our formulas, we should be able to find them that way.

**Comment by namurphy** [comment]
Starting to take a look now!  

`mass_number('N')` should be failing since `'N'` refers to nitrogen, and the particular isotope of nitrogen is not specified.  For neutrons, the call is `mass_number('n')`.

**Comment by StanczakDominik** [comment]
Coveralls seems to have forsaken this PR, but no matter! Thanks @pohzipohzi for the code and @namurphy for the review!

**Pull request merged**
