### PR TITLE
Clean up narrative documentation pages

### PR DESCRIPTION
**Pull request by namurphy**
This pull request is to add some structure to our [online documentation](https://readthedocs.org/projects/plasmapy/) and remove some placeholder items that were temporarily added while the docs were being set up.  I'm very new to [Sphinx](http://www.sphinx-doc.org/en/stable/) and have not yet figured out how to incorporate the docstrings from the different modules into the documentation.

Here is a [readthedocs page to test this pull request](http://test-plasmapy-docs.readthedocs.io/en/doc-atomic/).

Here are some cat emoticons: 🐱  🐈  😹 :octocat: 😹

### CODE REVIEW

**Comment by StanczakDominik** [comment]
Hey, I caught up on [some](https://pythonhosted.org/an_example_pypi_project/sphinx.html#auto-directives) [reading](https://pythonhosted.org/an_example_pypi_project/sphinx.html#full-code-example) and was able to include most of the autodoc stuff.

`electric_charge` was not in `__init__.py` so it wasn't visible to docs, but it is now.

There are some bugs with our TeX representation of equations, for example, `rac{e^{-x^2}}{x-zeta}` pops up in `plasmapy.math`. This was intended to be a `\frac`, which means some weird escape character shenanigan is going on.

**Comment by StanczakDominik** [comment]
Oh yeah, one more thing - maybe it'd be helpful to split the doc files for the `physics` subpackage, given I'm counting 6 independent files in there? They're all accessible via  ` from plasmapy.physics import whatever_plasmy` through imports in `__init__.py`, but if we just dump it into `physics` in the docs, that page is going to get really dense.

**Comment by StanczakDominik** [comment]
[I think I found the reason for TeX stuff going weird most of the time:](http://www.sphinx-doc.org/en/stable/ext/math.html)

 > Keep in mind that when you put math markup in Python docstrings read by autodoc, you either have to double all backslashes, or use Python raw strings (r"raw").

Guess we'll have to go through them and turn them into raw strings.

**Comment by namurphy** [comment]
Here are some RST and Sphinx resources that I might be finding helpful:
- [Online reStructuredText editor](http://rst.ninjs.org/#)
- [timstaley/sphinx-example](https://github.com/timstaley/sphinx-example)

**Comment by StanczakDominik** [comment]
Okay, this is kinda weird... none of the functions are appearing in the docs page, literally all of them are gone, but as I build the docs locally via `sphinx-build -b html docs/ docs_output` they're rendering perfectly fine, as visible below:

image

This is probably some visibility issue with sphinx not being able to import plasmapy.

**Comment by StanczakDominik** [comment]
Okay. Phew.

I managed to fix this via basically completely overhauling the living crud out of our packaging, bringing us closer to astropy packaging guidelines. See the current version in action [here](http://plasmapy-stanczakdominik-test.readthedocs.io/en/doc-atomic/index.html) and the code [here](https://github.com/StanczakDominik/PlasmaPy/tree/doc-atomic).

These are relatively huge changes, though, and some really careful code review on this one could be quite handy.

@namurphy, if you're okay with this I'll push the changes into this branch, so we can check it easier - otherwise I could finally learn `git cherrypick` and make another PR for those.

**Comment by StanczakDominik** [comment]
Oh yeah, there are a couple of buttons I had to press over at ReadTheDocs (see [point 17 here](http://docs.astropy.org/en/stable/development/affiliated-packages.html#managing-the-template-files-via-git)) to make this work.

**Comment by namurphy** [comment]
Thank you, @StanczakDominik!  I was wondering if it would be necessary to go through the process again after starting to use `astropy_helpers`.  I'm still getting familiar with those packaging guidelines but I didn't notice any issues with your changes.  Pushing the changes into this branch sounds good to me.

@colbych - Could you go into the main Read the Docs for PlasmaPy and make the following changes that were mentioned above?  It'd also be great if you could add @StanczakDominik and me as maintainers for the main project too.  My Read the Docs login is namurphy.  Thank you!

> If you want the documentation for your project to be hosted by Read the Docs, then you need to setup an account there. The following entries in “Advanced Settings” for your package on Read the Docs should work:
>
> - activate Install your project inside a virtualenv using setup.py install

> - activate Give the virtual environment access to the global site-packages dir.

> All other settings can stay on their default value.

**Comment by StanczakDominik** [comment]
So I tried rebasing this onto master to fix the merge conflict caused by my earlier update to the site address in `setup.py`... and I guess a side effect of that is plastering my face over every commit in this branch as "committed with".

Whoops.

**Comment by colbych** [comment]
Sorry guys I have been busy with moving/apartment hunting. I’ll ty to work on this tonight.

**Pull request merged**
