### PR TITLE
Update versions of `towncrier` and `sphinx-changelog`

### LINKED ISSUE #1851: Remove upper limit on allowed versions of `towncrier`
In #1850, we ended up pinning `towncrier` to `22.8.0` because there ended up being a discrepancy between `towncrier` and `sphinx-changelog`.  This appears to be because packages that depend on `towncrier` made use of its `Config` object, which is not part of the `towncrier` public API, and then `Config` got converted into a `dataclass`.  Once that issue is addressed upstream, we should revert that upper limit and change to `towncrier >= 22.8.0` or `towncrier >= 22.12.0`.  We'll need to wait until that issue is addressed upstream.

(I also added a title to `dev.rst` in #1850 to fix a separate (unrelated?) warning, so we should make sure the title still needed and appears okay.)

### PR DESCRIPTION
**Pull request by namurphy**
There had been an incompatibility between recent releases of towncrier and sphinx-changelog, so we had previously pinned the versions of these packages. The most recent release of sphinx-changelog should have resolved this incompatibility, so it should now be interoperable with the most recent release of towncrier.  This PR sets the most recent versions of towncrier and sphinx-changelog as lower limits in the requirements.  

Closes #1851. See also #1711 and #1717.

### CODE REVIEW

**Review by ejohnson-96 — APPROVED** [review]
Looks good :)

**Review by ejohnson-96 — CHANGES_REQUESTED** [review]
Merge conflicts arise when updating

**Comment by namurphy** [comment]
@ejohnson-96 — just fixed the conflicts that resulted from merging #2019.  Thanks!

**Review by ejohnson-96 — APPROVED** [review]
👍

**Pull request merged**
