### PR TITLE
Enable a `tox` extension to use `uv` instead of `pip` for installing all the things

### PR DESCRIPTION
**Pull request by namurphy**
This PR adds the [`tox-uv`](https://github.com/tox-dev/tox-uv) extension to [`tox`](https://tox.wiki) to make it so that [`uv`](https://github.com/astral-sh/uv) installs Python packages into `tox` environments and the creation of virtual environments.It also adds `tox-uv` into the `docs` and `tests` dependency sets so that when users run `tox` locally, virtual environment creation will be done with `uv`. 

The consequences of this PR are:

 - CI will be faster when reading from a cache by ∼10%
 - CI will be significantly faster
 - Running tests locally with tox will be faster.

`uv` is very new (the one-month anniversary of its release is today! 🎂), but work for the vast majority of common usages of `pip`.  We recently began using `uv` to generate our pinned requirements files in #2523. We also recently made some significant improvements to our CI by caching `.tox` in #2552. 

The risks of this PR are very low; if one of these packages stops being maintained, then we can revert this PR. 

If we decide to eventually switch from `tox` to [`nox`](https://nox.thea.codes/en/stable/usage.html) (#1734), it looks straightforward to use the `uv` backend for `nox`.

### CODE REVIEW

**Comment by namurphy** [comment]
I did some timings:

 - Python 3.12 tests, previous PR, using cached `.tox`: **42 s**
   - Reading cache: 6 s
   - Running tox environment: 36 s
 - Python 3.12 tests, this PR with `tox-uv`, regenerating cache of `.tox` (the cache was invalidated because I changed `pyproject.toml`):  **48 s**
   - Reading cache: 0 s 
   - Running tox environment: 48 s
 - Python 3.12 tests, this PR with `tox-uv`, using cached `.tox`: **39 s**
   - Reading cache: 4 s
   - Running tox environment 35 s

**Comment by namurphy** [comment]
Here's a table of the timings, since I want to share it with a few other projects:

| step        | #2569, rebuild cache | #2584, rebuild cache | #2584, use cached `.tox` |
| ----------- | -------------------- | -------------------- | ------------------------ |
| setup job   | 1                    | 2                    | 1                        |
| checkout    | 2                    | 2                    | 2                        |
| Python      | 3                    | 3                    | 3                        |
| install tox | 2                    | 3                    | 2                        |
| pre-cache   | 0                    | 0                    | 4                        |
| tox - setup | 147                  | 6                    | 2                        |
| tox - pytest| 33                   | 41                   | 33                       |
| post cache  | 7                    | 7                    | 0                        |
| **non-pytest, non-cache** | 155        | 16                   | 10 
| **total**   | 195                  | 64                   | 47                       |

**Review by StanczakDominik — APPROVED** [review]
Hell yeah, let's try it out! 😁

**Review by ejohnson-96 — APPROVED** [review]
👍

**Pull request merged**
