### PR TITLE
Put isotope data into JSON

### PR DESCRIPTION
**Pull request by StanczakDominik**
Continues [a discussion we've had on Matrix](https://matrix.to/#/!hkWCiyhQyxiYJlUtKF:matrix.org/$1546027415314043ntuti:matrix.org?via=matrix.org&via=openastronomy.org&via=cadair.com&via=t2bot.io). I dumped everything into json like this:
```python
In [41]: def convert(x): 
    ...:     if x.unit == u.u: 
    ...:         return x.value 
    ...:     else: 
    ...:         return x.si.value 
    ...:           
In [42]: with open("isotopes.json", "w") as f: 
    ...:     json.dump(isotopes._Isotopes, f, default=convert, indent=2) 
```

And, given that the diff is large, this is how I was able to recreate the dict with units:

```python
"""
Create a dictionary containing basic information for isotopes and
neutrons.
"""

import astropy.units as u
import json
import os

with open(os.path.join(os.path.dirname(__file__), "isotopes.json")) as f:
    _Isotopes = json.load(f)

for isotope in _Isotopes:         # I'm kind of suspecting that something smarter than a for loop could be done here
    _Isotopes[isotope]["mass"] *= u.u
    if "half-life" in _Isotopes[isotope] and not isinstance(
            _Isotopes[isotope]["half-life"], str):
        _Isotopes[isotope]["half-life"] *= u.s
````

As a check, with the old version imported and the new version in local scope:
```python
In [40]: isotopes._Isotopes == _Isotopes                                                                                                                           
Out[40]: True
```

### CODE REVIEW

**Comment by namurphy** [comment]
Putting the isotopes information into json format is a worthwhile idea.  It would probably make sense to do the same for `elements.py` for consistency.  Another possibility would be to create a json file containing information for particles and antiparticles, though this would be a little more involved since `special_particles.py` contains code that sets some of the particle attributes, so it could be relegated to another issue.  

Related issues: #18, #104, #275

**Comment by StanczakDominik** [comment]
By the way, before I forget - I realized that this will break pip installs due to `wheels`, and we'll probably need to update MANIFEST or some such black packaging magic and change up the `__file__` call for this to work.

**Comment by StanczakDominik** [comment]
* [ ] add note on adding manifest file to development guide

**Comment by StanczakDominik** [comment]
Note to self that vn-ki on Riot has a better implementation of the JSON parser.

**Pull request merged**
