### PR TITLE
Reshuffle subpackages (#576 followup)

### LINKED ISSUE #576: Reshuffle subpackages (plasmapy.theory)
From the telecon today and based on stuff that came up in #561, this is something that probably deserves wider discussion.

* [x] move `plasmapy.math`, `plasmapy.physics` and `plasmapy.transport` into a common `plasmapy.theory.*` subpackage (so we'd have `plasmapy.theory.math` etc)
* [x] possibly rename `physics` to `parameters` along the way
* [ ] fix all the import errors that this causes
* [ ] possibly fix docs
* [ ] possibly split up optional dependency pip install options again (see #561)

While an implementation is pretty easy and thus a good first contribution, whether we actually do it should wait until consensus is reached here.

### PR DESCRIPTION
**Pull request by StanczakDominik**
Closes #576

### CODE REVIEW

**Comment by StanczakDominik** [comment]
@pep8speaks pep8ify

**Comment by StanczakDominik** [comment]
@namurphy I forget if we decided we'd call the subpackage `theory` or `parameters` :( Probably the latter, right?

**Comment by namurphy** [comment]
> @namurphy I forget if we decided we'd call the subpackage `theory` or `parameters` :( Probably the latter, right?

Hm...I don't think it was `plasmapy.the_latter`.  It was `plasmapy.parameters` :cat:

**Comment by StanczakDominik** [comment]
Obsoleted once again by #692

**Pull request closed without merging**
