### PR TITLE
Remove deprecated T_i from gyroradius

### LINKED ISSUE #1814: Remove deprecated `T_i` argument from `gyroradius`
In #1170, we deprecated the `T_i` argument to `plasmapy.formulary.lengths.gyroradius`.  We've had a few releases since then, so it's probably safe to remove this, update the docstring and tests, and add a `breaking` changelog entry.

### PR DESCRIPTION
**Pull request by tranqver**
## Description
Removed deprecated T_i from plasmapy.formulary.lengths.gyroradius and the corresponding test inputs from PlasmaPy.formulary.tests.test_lengths.

## Related issues
Closes #1814

### CODE REVIEW

**Comment by namurphy** [comment]
Thank you for submitting this!  I think the only two things that are left are to [add a changelog entry](https://docs.plasmapy.org/en/latest/contributing/changelog_guide.html#adding-a-changelog-entry) and to add yourself to the list of authors at `docs/about/credits.rst`.

The Python 3.10 tests are failing because of an unrelated issue, which should be solved when #1822 is merged, hopefully soon!

**Comment by tranqver** [comment]
> Thank you for submitting this! I think the only two things that are left are to [add a changelog entry](https://docs.plasmapy.org/en/latest/contributing/changelog_guide.html#adding-a-changelog-entry) and to add yourself to the list of authors at `docs/about/credits.rst`.
> 
> The Python 3.10 tests are failing because of an unrelated issue, which should be solved when #1822 is merged, hopefully soon!

For the changelog entry, should I include information about the removed tests?

**Comment by namurphy** [comment]
> For the changelog entry, should I include information about the removed tests?

Nope, the changelog entry doesn't need to mention tests since the changes in tests can be assumed from the change in functionality.  The autoformatting from the pre-commit check can be done by adding a comment to this pull request that says `pre-commit.ci autofix`.  

As soon as #1822 is merged, then this should be just about ready to go!

**Comment by tranqver** [comment]
pre-commit.ci autofix

**Comment by namurphy** [comment]
For some reason the tests weren't picking up the changes from #1824 when I tried re-running them, so I did a `git pull` from `plasmapy/main` to pull those changes in and re-run the tests.  Since it looks ready to go once we make sure the tests pass, I'll set this to auto-merge.  Thank you again!

**Review by namurphy — APPROVED** [review]

**Pull request merged**
