### PR TITLE
[interoperability_tofu] Added tofu_import_error in optional_deps.py

### PR DESCRIPTION
**Pull request by Didou09**
Motivations:
--------------
* First attempt at contributing to the interoperability between [tofu](https://github.com/ToFuProject/tofu) and [PlasmaPy](https://github.com/PlasmaPy/PlasmaPy), starting with the basics of how PlasmaPy can handle optional affiliated packages
* more a fisrt contact to agree on how I'll contribute than a significant contribution really

Main changes:
----------------
* Feature: Added `tofu_import_error `in optional_deps.py

### CODE REVIEW

**Comment by rocco8773** [comment]
@Didou09 Thanks for initiating this conversation.  This week @namurphy and I are planning to outline how we classify "affiliated" and "community" packages, as well as, start the process of getting them on [PlasmaPy.org](https://www.plasmapy.org).  I want to get that complete and then come back to this PR sometime next week.

With that said,  I think a better approach here would be to create an `affiliates` key in the `setup.cfg` under `[options.extras_require]`.  Then a user could install all affiliated packages by doing...

```pip install plasmapy[affiliates]```

**Comment by Didou09** [comment]
OK, seems like a good idea, I'll wait for your input on how to proceed then

**Comment by rocco8773** [comment]
@Didou09 Sorry for taking so long with this.  Now that APS is over we can all refocus.

My current thoughts...I don't think we should add `tofu` to `plasmapy`'s dependencies nor `plasmapy` to `tofu`'s dependencies until interoperability is actually implemented.  That doesn't mean I think we should never do this, we just wait a little long until the implementation is made.  In the meantime, I'm working on establishing an "Affiliated Packages" page on PlasmaPy.org (see PR https://github.com/PlasmaPy/plasmapy.github.io/pull/80).  This would allow us to advertise `tofu` on PlsasmaPy.org.  I'm also thinking we could make a shield.io so that you can then put in your package that links back to the "Affiliated Packages" page.

To get the ball rolling, could you fill out this [google form](https://docs.google.com/forms/d/e/1FAIpQLSfz2djEihWkODbkr1ZC5splkX7ZKLAh_Kuy-aXOngTELIm3xQ/viewform?usp=sf_link).  Info submitted in this form will go into making `tofu`'s entry on the website.

**Comment by Didou09** [comment]
Hi @rocco8773 ,

I filled in the form, labelling tofu as 'affiliated' although it is not interoperable yet but should become so soon.

I'll include a reference to PlasmaPy in the next release,
Let me know your thoughts on my answer and about the next step

Best

**Comment by rocco8773** [comment]
Awesome! I got the submission.  Curious, are you able to back and edit your long description?  I accidentally had the max character count set to min character count and, thus, your long description is too long.

**Comment by Didou09** [comment]
I can try, but can you give me a link to my form?
Afaik I can't retrieve it myself

**Comment by rocco8773** [comment]
I sent you an email with the link, since I did not want to make it public on GitHub.

**Comment by StanczakDominik** [comment]
I'll close this since we're not using tofu yet (but we'll be keep on the lookout for functionality that might take advantage of it!) :smile:

**Pull request closed without merging**
